/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserPublic {
    id: UserId;
    country: Country;
    createdAt: Timestamp;
    role: Role;
    fullName: string;
    isActive: boolean;
    email: string;
    avatarRef?: FileRef;
}
export interface SupportProofPublic {
    id: bigint;
    files: Array<FileRef>;
    status: ReviewStatus;
    heroId: UserId;
    referenceNumber?: string;
    createdAt: Timestamp;
    adminNote?: string;
    caseId: bigint;
}
export interface FileRef {
    mimeType: string;
    fileName: string;
    storageId: string;
}
export type City = string;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface HelpSeekerStatsPublic {
    requestsSubmitted: bigint;
    requestsCompleted: bigint;
    requestsApproved: bigint;
}
export interface CasePublic {
    id: bigint;
    title: string;
    documents: Array<FileRef>;
    country: Country;
    city: City;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    deadline: Timestamp;
    adminNote?: string;
    amountNeeded: USDCents;
    category: Category;
    isPublic: boolean;
    verificationStatus: VerificationStatus;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CaseSummary {
    id: bigint;
    title: string;
    country: Country;
    city: City;
    createdAt: Timestamp;
    deadline: Timestamp;
    amountNeeded: USDCents;
    category: Category;
    verificationStatus: VerificationStatus;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type Country = string;
export interface PageRequest {
    offset: bigint;
    limit: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentPublic {
    id: bigint;
    status: PaymentStatus;
    createdAt: Timestamp;
    feeType: FeeType;
    amountCents: USDCents;
    caseId?: bigint;
    stripeSessionId: string;
    paidBy: UserId;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type USDCents = bigint;
export interface HeroStatsPublic {
    peopleHelped: bigint;
    casesSupported: bigint;
    proudHeartCount: bigint;
    casesCompleted: bigint;
    achievements: Array<Achievement>;
}
export interface ProudHeart {
    fromHelpSeeker: UserId;
    toHero: UserId;
    awardedAt: Timestamp;
    caseId: bigint;
}
export enum Achievement {
    TrustedHero = "TrustedHero",
    FirstSupport = "FirstSupport",
    TenPeopleHelped = "TenPeopleHelped",
    EducationHero = "EducationHero",
    MedicalHero = "MedicalHero",
    CommunityHero = "CommunityHero",
    FiftyPeopleHelped = "FiftyPeopleHelped"
}
export enum Category {
    Surgery = "Surgery",
    Orphans = "Orphans",
    Food = "Food",
    DebtRelief = "DebtRelief",
    Books = "Books",
    EmergencyNeeds = "EmergencyNeeds",
    Widows = "Widows",
    Uniform = "Uniform",
    Medicines = "Medicines",
    Employment = "Employment",
    DisabilitySupport = "DisabilitySupport",
    Medical = "Medical",
    Housing = "Housing",
    Transportation = "Transportation",
    UniversityFees = "UniversityFees",
    Other = "Other",
    SchoolFees = "SchoolFees",
    Education = "Education",
    Utilities = "Utilities"
}
export enum FeeType {
    ListingFee = "ListingFee",
    UnlockFee = "UnlockFee"
}
export enum PaymentStatus {
    Failed = "Failed",
    Confirmed = "Confirmed",
    Pending = "Pending"
}
export enum ReviewStatus {
    UnderReview = "UnderReview",
    Approved = "Approved",
    Rejected = "Rejected",
    Submitted = "Submitted",
    Completed = "Completed"
}
export enum Role {
    Hero = "Hero",
    HelpSeeker = "HelpSeeker",
    Admin = "Admin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationStatus {
    DocumentsSubmitted = "DocumentsSubmitted",
    InstitutionVerified = "InstitutionVerified",
    Unverified = "Unverified"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addCaseDocument(caseId: bigint, fileRef: FileRef): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardProudHeart(caseId: bigint, heroId: UserId): Promise<void>;
    banUser(userId: UserId): Promise<void>;
    computeAchievements(heroId: UserId): Promise<Array<Achievement>>;
    /**
     * / Confirm listing fee after Stripe session completes; records payment + wallet entry
     */
    confirmListingFee(stripeSessionId: string, caseId: bigint | null): Promise<PaymentPublic>;
    /**
     * / Confirm unlock fee after Stripe session completes
     */
    confirmUnlockFee(stripeSessionId: string, caseId: bigint): Promise<PaymentPublic>;
    createCase(title: string, description: string, category: Category, country: Country, city: City, amountNeeded: USDCents, deadline: Timestamp): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    /**
     * / Create a Stripe checkout session for the $1 listing fee
     */
    createListingFeeSession(successUrl: string, cancelUrl: string): Promise<string>;
    /**
     * / Create a Stripe checkout session for the $2 unlock fee
     */
    createUnlockFeeSession(caseId: bigint, successUrl: string, cancelUrl: string): Promise<string>;
    getAllCases(): Promise<Array<CasePublic>>;
    getAllProofs(): Promise<Array<SupportProofPublic>>;
    getAllUsers(): Promise<Array<UserPublic>>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseDetail(id: bigint): Promise<CasePublic | null>;
    getCaseSummary(id: bigint): Promise<CaseSummary | null>;
    getHelpSeekerStats(userId: UserId): Promise<HelpSeekerStatsPublic | null>;
    getHeroStats(userId: UserId): Promise<HeroStatsPublic | null>;
    getMyProofs(): Promise<Array<SupportProofPublic>>;
    getPendingPayments(): Promise<Array<PaymentPublic>>;
    getProofsForCase(caseId: bigint): Promise<Array<SupportProofPublic>>;
    getProudHeartsForHero(heroId: UserId): Promise<Array<ProudHeart>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUser(id: UserId): Promise<UserPublic | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isUnlocked(caseId: bigint): Promise<boolean>;
    listCases(category: Category | null, page: PageRequest): Promise<Array<CaseSummary>>;
    registerUser(fullName: string, email: string, role: Role): Promise<UserPublic>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitProof(caseId: bigint, files: Array<FileRef>, referenceNumber: string | null): Promise<bigint>;
    suspendUser(userId: UserId): Promise<void>;
    switchRole(newRole: Role): Promise<UserPublic>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unlockCase(caseId: bigint): Promise<void>;
    updateProofStatus(proofId: bigint, status: ReviewStatus, adminNote: string | null): Promise<void>;
    updateUserProfile(fullName: string, country: Country, avatarRef: FileRef | null): Promise<UserPublic>;
    updateVerificationStatus(caseId: bigint, status: VerificationStatus): Promise<void>;
}
import type { Achievement as _Achievement, CasePublic as _CasePublic, CaseSummary as _CaseSummary, Category as _Category, City as _City, Country as _Country, Error as _Error, FeeType as _FeeType, FileRef as _FileRef, HelpSeekerStatsPublic as _HelpSeekerStatsPublic, HeroStatsPublic as _HeroStatsPublic, PaymentPublic as _PaymentPublic, PaymentStatus as _PaymentStatus, Result as _Result, ReviewStatus as _ReviewStatus, Role as _Role, StripeSessionStatus as _StripeSessionStatus, SupportProofPublic as _SupportProofPublic, Timestamp as _Timestamp, USDCents as _USDCents, UserId as _UserId, UserPublic as _UserPublic, UserRole as _UserRole, VerificationStatus as _VerificationStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addCaseDocument(arg0: bigint, arg1: FileRef): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCaseDocument(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCaseDocument(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardProudHeart(arg0: bigint, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardProudHeart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardProudHeart(arg0, arg1);
            return result;
        }
    }
    async banUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async computeAchievements(arg0: UserId): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.computeAchievements(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeAchievements(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmListingFee(arg0: string, arg1: bigint | null): Promise<PaymentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmListingFee(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PaymentPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmListingFee(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PaymentPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmUnlockFee(arg0: string, arg1: bigint): Promise<PaymentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmUnlockFee(arg0, arg1);
                return from_candid_PaymentPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmUnlockFee(arg0, arg1);
            return from_candid_PaymentPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCase(arg0: string, arg1: string, arg2: Category, arg3: Country, arg4: City, arg5: USDCents, arg6: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0, arg1, to_candid_Category_n24(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0, arg1, to_candid_Category_n24(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createListingFeeSession(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createListingFeeSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListingFeeSession(arg0, arg1);
            return result;
        }
    }
    async createUnlockFeeSession(arg0: bigint, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUnlockFeeSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUnlockFeeSession(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllCases(): Promise<Array<CasePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCases();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCases();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProofs(): Promise<Array<SupportProofPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProofs();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProofs();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseDetail(arg0: bigint): Promise<CasePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseDetail(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseDetail(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseSummary(arg0: bigint): Promise<CaseSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseSummary(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseSummary(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelpSeekerStats(arg0: UserId): Promise<HelpSeekerStatsPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpSeekerStats(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpSeekerStats(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeroStats(arg0: UserId): Promise<HeroStatsPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroStats(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroStats(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProofs(): Promise<Array<SupportProofPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProofs();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProofs();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPayments(): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPayments();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPayments();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProofsForCase(arg0: bigint): Promise<Array<SupportProofPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProofsForCase(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProofsForCase(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProudHeartsForHero(arg0: UserId): Promise<Array<ProudHeart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProudHeartsForHero(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProudHeartsForHero(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isUnlocked(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUnlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUnlocked(arg0);
            return result;
        }
    }
    async listCases(arg0: Category | null, arg1: PageRequest): Promise<Array<CaseSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCases(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCases(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: Role): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n62(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserPublic_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n62(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserPublic_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitProof(arg0: bigint, arg1: Array<FileRef>, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProof(arg0, arg1, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProof(arg0, arg1, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async suspendUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async switchRole(arg0: Role): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.switchRole(to_candid_Role_n62(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.switchRole(to_candid_Role_n62(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unlockCase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockCase(arg0);
            return result;
        }
    }
    async updateProofStatus(arg0: bigint, arg1: ReviewStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProofStatus(arg0, to_candid_ReviewStatus_n65(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProofStatus(arg0, to_candid_ReviewStatus_n65(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: Country, arg2: FileRef | null): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, to_candid_opt_n67(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserPublic_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, to_candid_opt_n67(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserPublic_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVerificationStatus(arg0: bigint, arg1: VerificationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVerificationStatus(arg0, to_candid_VerificationStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVerificationStatus(arg0, to_candid_VerificationStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Achievement_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CasePublic_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CasePublic): CasePublic {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CaseSummary_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseSummary): CaseSummary {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FeeType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeType): FeeType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_HeroStatsPublic_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroStatsPublic): HeroStatsPublic {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPublic): PaymentPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SupportProofPublic_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportProofPublic): SupportProofPublic {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileRef]): FileRef | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CasePublic]): CasePublic | null {
    return value.length === 0 ? null : from_candid_CasePublic_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseSummary]): CaseSummary | null {
    return value.length === 0 ? null : from_candid_CaseSummary_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HelpSeekerStatsPublic]): HelpSeekerStatsPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HeroStatsPublic]): HeroStatsPublic | null {
    return value.length === 0 ? null : from_candid_HeroStatsPublic_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    createdAt: _Timestamp;
    feeType: _FeeType;
    amountCents: _USDCents;
    caseId: [] | [bigint];
    stripeSessionId: string;
    paidBy: _UserId;
}): {
    id: bigint;
    status: PaymentStatus;
    createdAt: Timestamp;
    feeType: FeeType;
    amountCents: USDCents;
    caseId?: bigint;
    stripeSessionId: string;
    paidBy: UserId;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n20(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        feeType: from_candid_FeeType_n22(_uploadFile, _downloadFile, value.feeType),
        amountCents: value.amountCents,
        caseId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.caseId)),
        stripeSessionId: value.stripeSessionId,
        paidBy: value.paidBy
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    documents: Array<_FileRef>;
    country: _Country;
    city: _City;
    createdAt: _Timestamp;
    createdBy: _UserId;
    description: string;
    deadline: _Timestamp;
    adminNote: [] | [string];
    amountNeeded: _USDCents;
    category: _Category;
    isPublic: boolean;
    verificationStatus: _VerificationStatus;
}): {
    id: bigint;
    title: string;
    documents: Array<FileRef>;
    country: Country;
    city: City;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    deadline: Timestamp;
    adminNote?: string;
    amountNeeded: USDCents;
    category: Category;
    isPublic: boolean;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        title: value.title,
        documents: value.documents,
        country: value.country,
        city: value.city,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        deadline: value.deadline,
        adminNote: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.adminNote)),
        amountNeeded: value.amountNeeded,
        category: from_candid_Category_n30(_uploadFile, _downloadFile, value.category),
        isPublic: value.isPublic,
        verificationStatus: from_candid_VerificationStatus_n32(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    files: Array<_FileRef>;
    status: _ReviewStatus;
    heroId: _UserId;
    referenceNumber: [] | [string];
    createdAt: _Timestamp;
    adminNote: [] | [string];
    caseId: bigint;
}): {
    id: bigint;
    files: Array<FileRef>;
    status: ReviewStatus;
    heroId: UserId;
    referenceNumber?: string;
    createdAt: Timestamp;
    adminNote?: string;
    caseId: bigint;
} {
    return {
        id: value.id,
        files: value.files,
        status: from_candid_ReviewStatus_n37(_uploadFile, _downloadFile, value.status),
        heroId: value.heroId,
        referenceNumber: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceNumber)),
        createdAt: value.createdAt,
        adminNote: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.adminNote)),
        caseId: value.caseId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    country: _Country;
    createdAt: _Timestamp;
    role: _Role;
    fullName: string;
    isActive: boolean;
    email: string;
    avatarRef: [] | [_FileRef];
}): {
    id: UserId;
    country: Country;
    createdAt: Timestamp;
    role: Role;
    fullName: string;
    isActive: boolean;
    email: string;
    avatarRef?: FileRef;
} {
    return {
        id: value.id,
        country: value.country,
        createdAt: value.createdAt,
        role: from_candid_Role_n42(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        avatarRef: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.avatarRef))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    country: _Country;
    city: _City;
    createdAt: _Timestamp;
    deadline: _Timestamp;
    amountNeeded: _USDCents;
    category: _Category;
    verificationStatus: _VerificationStatus;
}): {
    id: bigint;
    title: string;
    country: Country;
    city: City;
    createdAt: Timestamp;
    deadline: Timestamp;
    amountNeeded: USDCents;
    category: Category;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        title: value.title,
        country: value.country,
        city: value.city,
        createdAt: value.createdAt,
        deadline: value.deadline,
        amountNeeded: value.amountNeeded,
        category: from_candid_Category_n30(_uploadFile, _downloadFile, value.category),
        verificationStatus: from_candid_VerificationStatus_n32(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    peopleHelped: bigint;
    casesSupported: bigint;
    proudHeartCount: bigint;
    casesCompleted: bigint;
    achievements: Array<_Achievement>;
}): {
    peopleHelped: bigint;
    casesSupported: bigint;
    proudHeartCount: bigint;
    casesCompleted: bigint;
    achievements: Array<Achievement>;
} {
    return {
        peopleHelped: value.peopleHelped,
        casesSupported: value.casesSupported,
        proudHeartCount: value.proudHeartCount,
        casesCompleted: value.casesCompleted,
        achievements: from_candid_vec_n14(_uploadFile, _downloadFile, value.achievements)
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TrustedHero: null;
} | {
    FirstSupport: null;
} | {
    TenPeopleHelped: null;
} | {
    EducationHero: null;
} | {
    MedicalHero: null;
} | {
    CommunityHero: null;
} | {
    FiftyPeopleHelped: null;
}): Achievement {
    return "TrustedHero" in value ? Achievement.TrustedHero : "FirstSupport" in value ? Achievement.FirstSupport : "TenPeopleHelped" in value ? Achievement.TenPeopleHelped : "EducationHero" in value ? Achievement.EducationHero : "MedicalHero" in value ? Achievement.MedicalHero : "CommunityHero" in value ? Achievement.CommunityHero : "FiftyPeopleHelped" in value ? Achievement.FiftyPeopleHelped : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Confirmed: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "Failed" in value ? PaymentStatus.Failed : "Confirmed" in value ? PaymentStatus.Confirmed : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ListingFee: null;
} | {
    UnlockFee: null;
}): FeeType {
    return "ListingFee" in value ? FeeType.ListingFee : "UnlockFee" in value ? FeeType.UnlockFee : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Surgery: null;
} | {
    Orphans: null;
} | {
    Food: null;
} | {
    DebtRelief: null;
} | {
    Books: null;
} | {
    EmergencyNeeds: null;
} | {
    Widows: null;
} | {
    Uniform: null;
} | {
    Medicines: null;
} | {
    Employment: null;
} | {
    DisabilitySupport: null;
} | {
    Medical: null;
} | {
    Housing: null;
} | {
    Transportation: null;
} | {
    UniversityFees: null;
} | {
    Other: null;
} | {
    SchoolFees: null;
} | {
    Education: null;
} | {
    Utilities: null;
}): Category {
    return "Surgery" in value ? Category.Surgery : "Orphans" in value ? Category.Orphans : "Food" in value ? Category.Food : "DebtRelief" in value ? Category.DebtRelief : "Books" in value ? Category.Books : "EmergencyNeeds" in value ? Category.EmergencyNeeds : "Widows" in value ? Category.Widows : "Uniform" in value ? Category.Uniform : "Medicines" in value ? Category.Medicines : "Employment" in value ? Category.Employment : "DisabilitySupport" in value ? Category.DisabilitySupport : "Medical" in value ? Category.Medical : "Housing" in value ? Category.Housing : "Transportation" in value ? Category.Transportation : "UniversityFees" in value ? Category.UniversityFees : "Other" in value ? Category.Other : "SchoolFees" in value ? Category.SchoolFees : "Education" in value ? Category.Education : "Utilities" in value ? Category.Utilities : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DocumentsSubmitted: null;
} | {
    InstitutionVerified: null;
} | {
    Unverified: null;
}): VerificationStatus {
    return "DocumentsSubmitted" in value ? VerificationStatus.DocumentsSubmitted : "InstitutionVerified" in value ? VerificationStatus.InstitutionVerified : "Unverified" in value ? VerificationStatus.Unverified : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UnderReview: null;
} | {
    Approved: null;
} | {
    Rejected: null;
} | {
    Submitted: null;
} | {
    Completed: null;
}): ReviewStatus {
    return "UnderReview" in value ? ReviewStatus.UnderReview : "Approved" in value ? ReviewStatus.Approved : "Rejected" in value ? ReviewStatus.Rejected : "Submitted" in value ? ReviewStatus.Submitted : "Completed" in value ? ReviewStatus.Completed : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Hero: null;
} | {
    HelpSeeker: null;
} | {
    Admin: null;
}): Role {
    return "Hero" in value ? Role.Hero : "HelpSeeker" in value ? Role.HelpSeeker : "Admin" in value ? Role.Admin : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n58(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CasePublic>): Array<CasePublic> {
    return value.map((x)=>from_candid_CasePublic_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupportProofPublic>): Array<SupportProofPublic> {
    return value.map((x)=>from_candid_SupportProofPublic_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentPublic>): Array<PaymentPublic> {
    return value.map((x)=>from_candid_PaymentPublic_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaseSummary>): Array<CaseSummary> {
    return value.map((x)=>from_candid_CaseSummary_n49(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n24(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileRef | null): [] | [_FileRef] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Surgery: null;
} | {
    Orphans: null;
} | {
    Food: null;
} | {
    DebtRelief: null;
} | {
    Books: null;
} | {
    EmergencyNeeds: null;
} | {
    Widows: null;
} | {
    Uniform: null;
} | {
    Medicines: null;
} | {
    Employment: null;
} | {
    DisabilitySupport: null;
} | {
    Medical: null;
} | {
    Housing: null;
} | {
    Transportation: null;
} | {
    UniversityFees: null;
} | {
    Other: null;
} | {
    SchoolFees: null;
} | {
    Education: null;
} | {
    Utilities: null;
} {
    return value == Category.Surgery ? {
        Surgery: null
    } : value == Category.Orphans ? {
        Orphans: null
    } : value == Category.Food ? {
        Food: null
    } : value == Category.DebtRelief ? {
        DebtRelief: null
    } : value == Category.Books ? {
        Books: null
    } : value == Category.EmergencyNeeds ? {
        EmergencyNeeds: null
    } : value == Category.Widows ? {
        Widows: null
    } : value == Category.Uniform ? {
        Uniform: null
    } : value == Category.Medicines ? {
        Medicines: null
    } : value == Category.Employment ? {
        Employment: null
    } : value == Category.DisabilitySupport ? {
        DisabilitySupport: null
    } : value == Category.Medical ? {
        Medical: null
    } : value == Category.Housing ? {
        Housing: null
    } : value == Category.Transportation ? {
        Transportation: null
    } : value == Category.UniversityFees ? {
        UniversityFees: null
    } : value == Category.Other ? {
        Other: null
    } : value == Category.SchoolFees ? {
        SchoolFees: null
    } : value == Category.Education ? {
        Education: null
    } : value == Category.Utilities ? {
        Utilities: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Hero: null;
} | {
    HelpSeeker: null;
} | {
    Admin: null;
} {
    return value == Role.Hero ? {
        Hero: null
    } : value == Role.HelpSeeker ? {
        HelpSeeker: null
    } : value == Role.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    UnderReview: null;
} | {
    Approved: null;
} | {
    Rejected: null;
} | {
    Submitted: null;
} | {
    Completed: null;
} {
    return value == ReviewStatus.UnderReview ? {
        UnderReview: null
    } : value == ReviewStatus.Approved ? {
        Approved: null
    } : value == ReviewStatus.Rejected ? {
        Rejected: null
    } : value == ReviewStatus.Submitted ? {
        Submitted: null
    } : value == ReviewStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    DocumentsSubmitted: null;
} | {
    InstitutionVerified: null;
} | {
    Unverified: null;
} {
    return value == VerificationStatus.DocumentsSubmitted ? {
        DocumentsSubmitted: null
    } : value == VerificationStatus.InstitutionVerified ? {
        InstitutionVerified: null
    } : value == VerificationStatus.Unverified ? {
        Unverified: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
